### ISSUE TITLE
Navigation überarbeiten

### ISSUE THREAD

**Issue by nilshindermann** [nilshindermann/AzubiManagementTool#3]
Aktuelle Navigation führt im schlimmsten Fall zu einem Absturz.
Ausserdem übernimmt es Änderungen der Daten, ohne auf *Speichern* gedrückt zu haben.

Vielleicht sollte der "Vor"-Knopf entfernt werden 🤔

**Comment by KolaSiro** [comment]
Wenn die Datenbank ganz leer ist und auf den Knopf 'Lernende' 1x geklickt wird, dauert es ca. 10 Sekunden, dann stürzt das Programm ab.

**Comment by nilshindermann** [comment]
Das Programm dürfte nicht mehr abstürzen
